# Generated by Django 2.2.9 on 2020-01-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
        migrations.AddField(
            model_name='customtext',
            name='test',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
